dist: xenial
language: node_js
node_js:
  - "10"
services:
  - redis
  - mongodb
cache: npm
install:
    - "cd home-base && npm install"
script:
    - "npm run test"
after_success:
    - "npm run coverage"